# Generated by Django 3.0.6 on 2022-06-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(upload_to='accessories')),
                ('image2', models.ImageField(blank=True, upload_to='accessories')),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='CoffeeBeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(upload_to='coffee_beans')),
                ('image2', models.ImageField(blank=True, upload_to='coffee_beans')),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Coffee Beans',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(upload_to='coffee_machines')),
                ('image2', models.ImageField(blank=True, upload_to='coffee_machines')),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Coffee Machines',
            },
        ),
        migrations.CreateModel(
            name='CoffeeMugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(upload_to='coffee_mugs')),
                ('image2', models.ImageField(blank=True, upload_to='coffee_mugs')),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Coffee Mugs',
            },
        ),
    ]
