# Generated by Django 3.0.6 on 2022-06-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(blank=True, max_length=100)),
                ('long_desc', models.TextField(blank=True, max_length=500)),
                ('image1', models.ImageField(upload_to='product_images')),
                ('image2', models.ImageField(blank=True, upload_to='product_images')),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_store.Category')),
            ],
        ),
    ]
