# Generated by Django 3.0.6 on 2022-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
