# Generated by Django 3.0.6 on 2022-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0003_auto_20220610_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(),
        ),
    ]
