# Generated by Django 3.0.6 on 2022-06-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0005_auto_20220610_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
