# Generated by Django 3.0.6 on 2022-06-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20220612_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
    ]
